version: '3.5'

services:
    simple-laravel-server:
        container_name: simple-laravel-server
        build:
            context: ./
            dockerfile: ./docker/nginx.Dockerfile
        ports:
            - "8080:80"
        volumes:
            - .:/var/www/html
        depends_on:
            - simple-laravel-app
    simple-laravel-app:
        container_name: simple-laravel-app
        image: php:8.1.3-fpm-alpine3.15
        ports:
            - "9000:9000"
        volumes:
            - .:/var/www/html
